---

- name: Installing required packages
  apt: name={{item}}
       state=latest
       update_cache=yes
  with_items:
    - python3
    - python3-pip
    - python3-dev
    - python3-setuptools
    - python3-venv
    - libyaml-dev
    - build-essential
    - libffi-dev
    - libssl-dev
    - avahi-daemon
  become: yes
  tags:
    - init


- name: Create user config directory.
  file:
    path: "{{ octoprint_install_path }}/.octoprint/"
    state: directory
    owner: "{{ octoprint_user }}"
    group: "{{ octoprint_user }}"
  become: yes

- name: Install octoprint via pip (this takes a while)
  pip:
    name: "{{ octoprint_url }}"
    virtualenv: "{{ octoprint_install_path }}/venv"
    virtualenv_command: virtualenv
    state: present
  become: yes

# - name: Install config.yaml template.
#   template:
#     src: config.yaml.j2
#     dest: "{{ octoprint_install_path }}/.octoprint/config.yaml"
#     owner: "{{ octoprint_user }}"
#   when: reset_config

# - name: Install init template.
#   template:
#     src: octoprint.init.j2
#     dest: /etc/init.d/octoprint
#     mode: +x
#     owner: "{{ octoprint_user }}"

# - name: Install default template.
#   template:
#     src: octoprint.default.j2
#     dest: /etc/default/octoprint
#     owner: "{{ octoprint_user }}"

- name: Install OctoPrint systemd Unit
  template: src=octoprint.service.j2
            dest=/etc/systemd/system/octoprint.service
  become: yes

- name: Add lines to sudoers
  lineinfile:
    path: /etc/sudoers
    state: present
    line: "{{ item }}"
    validate: /usr/sbin/visudo -cf %s
  loop:
    - "{{ octoprint_user }} ALL=(ALL) NOPASSWD:/usr/bin/systemctl restart octoprint"
    - "{{ octoprint_user }} ALL=(ALL) NOPASSWD:/usr/bin/systemctl start octoprint"
    - "{{ octoprint_user }} ALL=(ALL) NOPASSWD:/usr/bin/systemctl stop octoprint"
    - "{{ octoprint_user }} ALL=(ALL) NOPASSWD:/usr/bin/systemctl restart mjpg_streamer"
    - "{{ octoprint_user }} ALL=(ALL) NOPASSWD:/usr/bin/systemctl start mjpg_streamer"
    - "{{ octoprint_user }} ALL=(ALL) NOPASSWD:/usr/bin/systemctl stop mjpg_streamer"
    - "{{ octoprint_user }} ALL=(ALL) NOPASSWD:/usr/sbin/shutdown -r now"
    - "{{ octoprint_user }} ALL=(ALL) NOPASSWD:/usr/sbin/shutdown -h now"
  become: yes

- name: Change ownership of install directory
  file:
    path: "{{ octoprint_install_path }}"
    state: directory
    recurse: true
    owner: "{{ octoprint_user }}"
    group: "{{ octoprint_user }}"
  become: yes

- name: Start octoprint service.
  systemd:
    name: octoprint
    enabled: true
    state: restarted
    daemon_reload: true
  become: yes