all:
  hosts:
    octopi.local:
      ansible_host: octopi.local
      ip: 192.168.14.19
    octopi.local:
      ansible_host: octopi.local
      ip: 192.168.14.19
    devops01.local:
      ansible_host: devops01.local
      ip: 127.0.0.1
      ansible_connection: local
  children:
    printing:
      hosts:
        octopi.local:
    dual:
      hosts:
        octopi.local:
  vars:
    ansible_user: pirate
    ansible_connection: ssh
    ansible_python_interpreter: /usr/bin/python3