all:
  children:
    raspberrypi:
      hosts:
        raspberrypi1:
          ansible_host: 192.168.0.10
        raspberrypi2:
          ansible_host: 192.168.0.11
        raspberrypi3:
          ansible_host: 192.168.0.12
        raspberrypi4:
          ansible_host: 192.168.0.13
        raspberrypi5:
          ansible_host: 192.168.0.14
    wireguard:
      hosts:
        wireguard1:
          ansible_host:
      vars:
        ansible_user: pirate
        ansible_connection: ssh
        ansible_python_interpreter: /usr/bin/python3