- name: Include setup tasks
  include_tasks: setup.yml

- name: Start Gitea container
  docker_container:
    name: gitea
    image: gitea/gitea:latest
    state: started
    restart_policy: always
    ports:
      - "80:3000"
      - "22:2222"
    volumes:
      - "/opt/gitea:/data"
