
network_interface: eth0
ipv4_static: True
ipv4_address: "{{ hostvars[inventory_hostname]['ansible_' + network_interface]['ipv4']['address'] }}"
dns_servers:
  - "8.8.8.8"
  - "8.8.4.4"

my_domain: local
my_timezone: "Europe/Berlin"
 


# OctoPrint config
octoprint_update: True
octoprint_git_repo: "https://github.com/OctoPrint/OctoPrint.git"
octoprint_url: "https://get.octoprint.org/latest"
octoprint_install_path: "/opt/octoprint"
octoprint_user: "pirate"
octoprint_group: "pirate"
octoprint_haproxy: True
octoprint_port: 5000
octoprint_webcam_port: 8080