

fspath_web_interface: "/var/www/admin"
fspath_web_directory: "/var/www/pihole"
fspath_pihole: "/opt/pihole"
fspath_pihole_src: "/etc/.pihole"
fspath_pihole_config: "/etc/pihole"

network_interface: eth0
ipv4_static: True
ipv4_address: "{{ hostvars[inventory_hostname]['ansible_' + network_interface]['ipv4']['address'] }}"
dns_servers:
  - "8.8.8.8"
  - "8.8.4.4"