---

- name: Install network tools
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
  loop:
    - ifupdown
    - net-tools
  tags: network

# - import_tasks: hostname.yml
#   tags:
#     - network

# - import_tasks: interfaces.yml
#   tags:
#     - network

- import_tasks: pihole.yml
  tags:
    - pihole