- name: Install Docker and Docker Compose
  apt:
    name:
      - docker.io
      - docker-compose
    state: present

# - name: Pull pihole Docker image
#   docker_image:
#     name: ghcr.io/pi-hole/pihole
#     tag: latest
#     pull: yes

- name: Create /opt/pihole directory
  become: yes
  file:
    path: /opt/pihole
    state: directory
    mode: 0755

- name: Copy docker-compose.yml template
  template:
    src: docker-compose.yml.j2
    dest: /opt/pihole/docker-compose.yml

- name: Start Pi-hole container
  command: docker-compose -f /opt/pihole/docker-compose.yml up -d
